#!/bin/bash
# Icon Generator Helper for PWA
# This script provides instructions for creating proper PWA icons

echo "🎨 PWA Icon Generation Helper"
echo "=============================="
echo ""
echo "You need to create the following PNG images and place them in: frontend/public/icons/"
echo ""
echo "REQUIRED ICONS (minimum):"
echo "├── icon-192x192.png (home screen icon)"
echo "├── icon-512x512.png (splash screen, install dialog)"
echo "└── apple-touch-icon-180x180.png (iOS home screen)"
echo ""
echo "RECOMMENDED (Adaptive Icons for Android 8+):"
echo "├── icon-192x192-maskable.png"
echo "└── icon-512x512-maskable.png"
echo ""
echo "OPTIONAL (Screenshots):"
echo "├── screenshot-540x720.png (narrow, mobile)"
echo "└── screenshot-1280x720.png (wide, tablet)"
echo ""
echo "────────────────────────────────────────────"
echo "ONLINE TOOLS TO GENERATE ICONS (FREE):"
echo "────────────────────────────────────────────"
echo "1. PWA Asset Generator"
echo "   https://tomayac.github.io/pwa-asset-generator/"
echo "   - Upload your 512x512 PNG"
echo "   - Auto-generates all sizes"
echo ""
echo "2. Favicon Generator"
echo "   https://www.favicon-generator.org/"
echo "   - Upload base image"
echo "   - Get all sizes"
echo ""
echo "3. Canva (Design)"
echo "   https://www.canva.com/create/icons/"
echo "   - Design custom icons"
echo "   - Export at different sizes"
echo ""
echo "4. ImageMagick (Command Line - if installed)"
echo "   convert input.png -resize 192x192 frontend/public/icons/icon-192x192.png"
echo ""
echo "────────────────────────────────────────────"
echo "ICON REQUIREMENTS:"
echo "────────────────────────────────────────────"
echo "• Format: PNG (for transparency)"
echo "• Minimum size: 192x192 (should be larger)"
echo "• Square: Must be square (1:1 aspect ratio)"
echo "• Transparent background: Recommended"
echo "• Safe margin: 10% padding on all sides"
echo "• Color: Match your theme (#667eea recommended)"
echo ""
echo "────────────────────────────────────────────"
echo "QUICK START:"
echo "────────────────────────────────────────────"
echo "1. Go to: https://tomayac.github.io/pwa-asset-generator/"
echo "2. Upload your 512x512 icon image"
echo "3. Click 'Generate'"
echo "4. Download ZIP"
echo "5. Extract into: frontend/public/icons/"
echo ""
echo "Then run:"
echo "  cd frontend"
echo "  npm run build"
echo "  git add -A && git commit -m 'add: PWA icons' && git push"
echo ""
